version: '3.1'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    networks:
#      - my_network
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#networks:
#  my_network:
#    driver: bridge
#
#volumes:
#  postgres_data:
