package project.valery.SoloRandomizer.randomizer.names;

import org.springframework.stereotype.Component;

@Component
public enum SmallMoveName implements MoveName {
    APPLE_JACKS(2, 4),
    BALL_STEP(1, 2, 3, 4),
    BALL_STEP_BRUSH(2),
    BALL_STEP_KICK(2),
    BALL_STEP_STEP(2),
    BOOGIE_BACK(2,4),
    BOOGIE_DROP4(4),
    BOOGIE_DROP_FOR2(2,4),
    BOOGIE_FORWARD(2,4),
    BOOGIE_STEP(2,3,4),

    BREAK_A_LEG(2,4),
    BREAK_HALF(4),
    BRUSH(1,2,3,4),
    BRUSH_BALL_STEP(2,4),
    BRUSH_HEEL(2,4),
    BRUSH_SKIP(2,4),
    BRUSH_STEP(2,4);

    private final int[] counts;

    SmallMoveName(int... counts) {
        this.counts = counts;
    }

    @Override
    public int[] getCountsArray() {
        return counts;
    }

    @Override
    public String getType() {
        return "Small";
    }
}




//    ,
//    ,

//    BUTTROLL,
//    CAKEWALK,
//    CAMELWALK,
//    CHARLESTON_40S,
//    CHARLESTON_JUMP,
//    CHARLESTON_SQUAT,
//    CHASES,
//    COW_TAIL,
//    CRAZY_BANANA,
//    CRAZY_LEG,
//    CROSS_STEP,
//    CROSS_STEP_SHORT,
//    DUCK_WALK,
//    EAGLE_SLIDE_FULL,
//    EAGLE_SLIDE_SHORT,
//    FALL_OFF_THE_LOG,
//    FISHTAILS_FOR_QUICK,
//    FISHTAILS_FOR_SLOW,
//    FORWARD_AND_BACK,
//    FREEZE,
//    GAZE_AFAR_FULL,
//    GAZE_AFAR_SHORT,
//    GRAPEVINE_FOR_QUICK,
//    GRAPEVINE_FOR_SLOW,
//    GRAPEVINE_FOR_STEP_BALL_STEP,
//    HALLELUJAHS,
//    HEEL,
//    HEEL_BRUSH,
//    HEELS,
//    HIGH_KICK,
//    INSIDE_TWIST_FOR_QUICK,
//    INSIDE_TWIST_FOR_SLOW,
//    ITCHES,
//    JUMP_FOR_QUICK,
//    JUMP_FOR_SLOW,
//    JIG_WALK,
//    KICK,
//    KICK_BALL_STEP,
//    KICK_BALL_TOUCH,
//    KICK_STEP,
//    KNEE_SLAP,
//    LEON_SLIDE,
//    LOCKSTEP_TERN_FOR_QUICK,
//    LOCKSTEP_TERN_FOR_SLOW,
//    MAGIK_FINGER,
//    MAMBO_STEPS,
//    MAXI_STOP,
//    MESS_AROUND,
//    OPPOSITES,
//    OUTSIDE_TWIST_FOR_QUICK,
//    OUTSIDE_TWIST_FOR_SLOW,
//    PAS_DE_BOURREE,
//    PECKS,
//    PIVOT_INSIDE,
//    PIVOT_OUTSIDE,
//    PIVOT_PREP_INSIDE,
//    PIVOT_PREP_OUTSIDE,
//    POINTS,
//    PUSH_IT,
//    PUSH_IT_FOR_THE_END,
//    QUIKE,
//    ROCK_AND_GO,
//    ROCK_AND_KICK,
//    ROCK_AND_LOCK,
//    ROCK_AND_LOCK_TERN,
//    ROCK_AND_SIDE,
//    ROCK_AND_TOUCH,
//    ROCK_STAP,
//    ROCKS,
//    RONDESTEP_BACK_FOR_QUICK,
//    RONDESTEP_BACK_FOR_SLOW,
//    RUSTY_DUSTY,
//    SAVOY_KICKS,
//    SCARECROW,
//    SCISSOR_KICKS,
//    SKIP,
//    SKIP_BRUSH,
//    SKIP_SKIP,
//    SHIMMY,
//    SHOE_SHINE_ONE_SHOE,
//    SHOE_SHINE_TWO_SHOES,
//    SHORT_GEORGE,
//    SKATE_ONE_LEG,
//    SKATE_TWO_LEGS,
//    SKIP_BRUSH,
//    SKIP_KICK,
//    SKIP_SLIDE,
//    SKIP_STEP,
//    SKIP_TOUCH,
//    SLID_QUICK_TOUCH,
//    SLIDE_QUICK,
//    SLIDE_QUICK_BRUSH,
//    SLIDE_SLOW,
//    SLIDE_SLOW_BRUSH,
//    SLIP_SLOPS,
//    SLOW,
//    SMASH_POTATO,
//    SPANK_THE_BABY,
//    STEP_AND_BRUSH,
//    STEP_BALL_TOUCH,
//    STEP_BRUSH,
//    STEP_FREEZE,
//    STEP_KICK,
//    STEP_TOUCH,
//    STOMP_OFF,
//    SUZIE_Q,
//    SWIVELS_STEPS,
//    TABBY_THE_CAT_FULL,
//    TABBY_THE_CAT_SHORT,
//    TACKY_ANNIE,
//    TICK_TACK,
//    TOUCH,
//    TOUCH_SLIDE,
//    TOUCH_STEP,
//    TRIPLESTEP,
//    TWISTS_QUICK,
//    TWISTS_SLOW
//}
